### ISSUE TITLE
Nextjs 13에서는 많은 변화가 생겼습니다.

### ISSUE THREAD

**Issue by Nayejun** [project-DIG/Daliy-In-Gsm-Frontend#1]
package.json을 보니 nextjs 버전이 13이시던데
**nextjs 13에서는 많은 변화가 생겼습니다.**

[(https://nextjs.org/blog/next-13)](https://nextjs.org/blog/next-13)
**위의 공식문서** 를 보시고 점진적으로 ``nextjs 13`` 을 적용해보심을 추천드립니다.

+공식문서에서는 ``i18n`` 을 지원하지 않기에, 영어로 된 원서를 읽는데 어려움이 있으시다면
[(https://mechaniccoder.tistory.com/20)](https://mechaniccoder.tistory.com/20)
**위의 글** 을 참고해주세요.

**Comment by jongjin1010** [comment]
관심 가져주셔서 감사합니다. 위의 글 꼭 참고 하겠습니다.
